// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCave8RrUQe8rJmhLKPwk6X5OyCi2uWa5o',
    appId: '1:301397469876:web:8aab5d246c1909fb0a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    authDomain: 'myvault-0602.firebaseapp.com',
    storageBucket: 'myvault-0602.firebasestorage.app',
    measurementId: 'G-WK3WH610VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGcX56yVm05uTcGUTltC-Fg9997MwVRI',
    appId: '1:301397469876:android:96837e0ef70f78860a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    storageBucket: 'myvault-0602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKZwSR5hT-bX5rSVnQxswdftUDhDiU0I',
    appId: '1:301397469876:ios:2cf16efd39b1c52c0a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    storageBucket: 'myvault-0602.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKZwSR5hT-bX5rSVnQxswdftUDhDiU0I',
    appId: '1:301397469876:ios:2cf16efd39b1c52c0a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    storageBucket: 'myvault-0602.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCave8RrUQe8rJmhLKPwk6X5OyCi2uWa5o',
    appId: '1:301397469876:web:447a386dcb895a640a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    authDomain: 'myvault-0602.firebaseapp.com',
    storageBucket: 'myvault-0602.firebasestorage.app',
    measurementId: 'G-YT2814RKQJ',
  );
}
