// File generated by FlutterFire CLI.
// Modified to load Firebase API keys from .env.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: '1:301397469876:web:8aab5d246c1909fb0a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    authDomain: 'myvault-0602.firebaseapp.com',
    storageBucket: 'myvault-0602.firebasestorage.app',
    measurementId: 'G-WK3WH610VW',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    appId: '1:301397469876:android:96837e0ef70f78860a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    storageBucket: 'myvault-0602.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:301397469876:ios:2cf16efd39b1c52c0a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    storageBucket: 'myvault-0602.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:301397469876:ios:2cf16efd39b1c52c0a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    storageBucket: 'myvault-0602.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY']!,
    appId: '1:301397469876:web:447a386dcb895a640a05e1',
    messagingSenderId: '301397469876',
    projectId: 'myvault-0602',
    authDomain: 'myvault-0602.firebaseapp.com',
    storageBucket: 'myvault-0602.firebasestorage.app',
    measurementId: 'G-YT2814RKQJ',
  );
}
